import { ProductType } from "@/enums";


export const dummyProducts:Product[] = [
  {
    productType: ProductType.BAGS,
    id: "1",
    name:"Chanel Classic Flap",
    barcode: Math.floor(Math.random() * 230).toString(),
    price: 34000,
    image_url: "/images/static/bag1.png",
    description: "Diamond Encrusted, Size 8",
    stock_quantity: 20,
  },
  {
    productType: ProductType.BAGS,
    id: "2",
    name:"Prada Saffiano Lux Tote",
    barcode: Math.floor(Math.random() * 230).toString(),
    price: 24000,
    image_url: "/images/static/bag2.png",
    description: "100% Leather",
    stock_quantity: 15,
  },
  {
    productType: ProductType.BAGS,
    id: "3",
    name:"Herm s Birkin",
    barcode: Math.floor(Math.random() * 230).toString(),
    price: 2500,
    image_url: "/images/static/bag3.png",
    description: "Diamond Encrusted, Size 8",
    stock_quantity: 30,
  },
  {
    productType: ProductType.BAGS,
    id: "4",
    name:"Gucci Bag Marmont",
    barcode: Math.floor(Math.random() * 230).toString(),
    price: 95000,
    image_url: "/images/static/bag4.png",
    description: "100% Leather",
    stock_quantity: 4,
  },
  {
    productType: ProductType.BAGS,
    id: "5",
    name:"Louis Vuitton Neverfull MM",
    barcode: Math.floor(Math.random() * 230).toString(),
    price: 34000,
    image_url: "/images/static/bag4.png",
    description: "100% Leather",
    stock_quantity: 20,
  },
  {
    productType: ProductType.JEWELRY,
    id: "6",
    name:"Chanel Wallet",
    barcode: Math.floor(Math.random() * 230).toString(),
    price: 16000,
    image_url: "/images/static/bag2.png",
    description: "100% Leather",
    stock_quantity: 10,
  },
  {
    productType: ProductType.PERFUMES,
    id: "7",
    name:"Herm s Wallet",
    barcode: Math.floor(Math.random() * 230).toString(),
    price: 12000,
    image_url: "/images/static/bag1.png",
    description: "100% Leather",
    stock_quantity: 25,
  },
  {
    productType: ProductType.BAGS,
    id: "8",
    name:"Gucci Wallet",
    barcode: Math.floor(Math.random() * 230).toString(),
    price: 10000,
    image_url: "/images/static/bag3.png",
    description: "100% Leather",
    stock_quantity: 15,
  },
  {
    productType: ProductType.BAGS,
    id: "9",
    name:"Prada Wallet",
    barcode: Math.floor(Math.random() * 230).toString(),
    price: 8000,
    image_url: "/images/static/bag2.png",
    description: "100% Leather",
    stock_quantity: 20,
  },
  {
    productType: ProductType.BAGS,
    id: "10",
    name:"Louis Vuitton Pochette",
    barcode: Math.floor(Math.random() * 230).toString(),
    price: 6000,
    image_url: "/images/static/bag4.png",
    description: "100% Leather",
    stock_quantity: 10,
  },
  {
    productType: ProductType.BAGS,
    id: "11",
    name:"Cartier Wallet",
    barcode: Math.floor(Math.random() * 230).toString(),
    price: 4500,
    image_url: "/images/static/bag1.png",
    description: "100% Leather",
    stock_quantity: 20,
  }
]
